# importing libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading the dataset

In [2]:
df=pd.read_csv('Wine_Quality_dataset.csv')

# getting first 5 rows of the dataframe

In [5]:
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


# Getting summary of the data like mean,mod,min,max etc

In [8]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000   
mean        7.216579          0.339691     0.318722        5.444326   
std         1.296750          0.164649     0.145265        4.758125   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6495.000000          6497.000000           6497.000000  6497.000000   
mean      0.056042            30.525319            115.744574     0.994697   
std       0.035036            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6488.000000  6493.000000  6497.000000  6497.000000  
mean      3.218395     0.531215    10.491801     5.818378  
std       0.160748     0.148814     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

# Column names of the dataset 


In [10]:
df.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

# Removing nan values

In [36]:
df.isna().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

# filling Nan values with mean of the dataframe

In [38]:
df=df.fillna(df.mean())

C:\Users\salma\AppData\Local\Temp\ipykernel_17144\3358723971.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df=df.fillna(df.mean())


# getting shape of the dataset

In [39]:
df.shape

(6497, 13)

In [40]:
 df.type

0       white
1       white
2       white
3       white
4       white
        ...  
6492      red
6493      red
6494      red
6495      red
6496      red
Name: type, Length: 6497, dtype: object

In [41]:
df['quality'].value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

# define independent and dependent variables

In [42]:
y=df['quality']

In [43]:
y.shape

(6497,)

In [44]:
y.unique()

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)

In [45]:
x=df.drop(['type','quality'],axis=1)

In [46]:
x.shape

(6497, 11)

In [47]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6492            6.2             0.600         0.08             2.0      0.090   
6493            5.9             0.550         0.10             2.2      0.062   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00   0.450000   
1                    14.0                 132.0  0.99400  3.30   0.490000   
2                    30.0                  97.0  0.99510  3.26   0.440000   
3                    47.0                 186.0  0.99560  3.19   0.400000   
4                    47.0                 186.0  0.99560  3.19   0.400000   
...                   ...                   ...      ...   ...        ...   
6492                 32.0                  44.0  0.99490  3.45   0.580000   
6493                 39.0                  51.0  0.99512  3.52   0.531215   
6494                 29.0                  40.0  0.99574  3.42   0.750000   
6495                 32.0                  44.0  0.99547  3.57   0.710000   
6496                 18.0                  42.0  0.99549  3.39   0.660000   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
6492     10.5  
6493     11.2  
6494     11.0  
6495     10.2  
6496     11.0  

[6497 rows x 11 columns]

# now scale the data

In [48]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scaled_data=scalar.fit_transform(x)

In [49]:
scaled_data

array([[-0.1671586 , -0.4235636 ,  0.28424515, ..., -1.35966451,
        -0.5459591 , -1.41855821],
       [-0.70742728, -0.24123152,  0.14652315, ...,  0.50804501,
        -0.27706392, -0.83161516],
       [ 0.68183504, -0.36278624,  0.55968916, ...,  0.25901707,
        -0.6131829 , -0.32852111],
       ...,
       [-0.70742728,  1.03509307, -1.2995579 , ...,  1.25512882,
         1.47075478,  0.42611996],
       [-1.01615224,  1.85558744, -1.3684189 , ...,  2.18898358,
         1.2018596 , -0.2446721 ],
       [-0.938971  , -0.18045416,  1.04171618, ...,  1.06835787,
         0.86574062,  0.42611996]])

In [50]:
scaled_data.shape

(6497, 11)

# Now split the data into train and test

In [55]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(scaled_data,y,test_size=0.3,random_state=0)

In [56]:
x_train.shape,y_train.shape

((4547, 11), (4547,))

In [57]:
x_test.shape,y_test.shape

((1950, 11), (1950,))

# Get model trained

In [58]:
from sklearn.svm import SVC
classifier=SVC(kernel='rbf',random_state=0)
classifier.fit(x_train,y_train)

SVC(random_state=0)

# get model's prediction

In [59]:
y_pred=classifier.predict(x_test)

In [60]:
y_pred

array([6, 5, 6, ..., 6, 6, 5], dtype=int64)

# model evaluation

In [61]:
from sklearn.metrics import confusion_matrix,classification_report

In [62]:
cnf=confusion_matrix(y_test,y_pred)
cnf

array([[  0,   0,   5,   2,   0,   0],
       [  0,   0,  39,  25,   1,   0],
       [  0,   0, 416, 245,   2,   0],
       [  0,   0, 174, 626,  39,   0],
       [  0,   0,   7, 250,  61,   0],
       [  0,   0,   0,  46,  12,   0]], dtype=int64)

In [64]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         7
           4       0.00      0.00      0.00        65
           5       0.65      0.63      0.64       663
           6       0.52      0.75      0.62       839
           7       0.53      0.19      0.28       318
           8       0.00      0.00      0.00        58

    accuracy                           0.57      1950
   macro avg       0.28      0.26      0.26      1950
weighted avg       0.53      0.57      0.53      1950



C:\Users\salma\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\salma\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\salma\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Get model re-run on two classes of wine 


In [65]:
y=df['quality'].apply(lambda y_value:1 if y_value>=6 else 0)

In [66]:
y.value_counts()

1    4113
0    2384
Name: quality, dtype: int64

# split the dataset into training and testing again 

In [67]:
x_train2,x_test2,y_train2,y_test2=tts(scaled_data,y,test_size=0.3,random_state=0)

In [68]:
x_train2.shape,x_test2.shape

((4547, 11), (1950, 11))

In [69]:
y_train2.shape,y_test2.shape

((4547,), (1950,))

# create another instance of the model

In [71]:
from sklearn.svm import SVC
clf=SVC(kernel='rbf',random_state=0)
clf.fit(x_train2,y_train2)

SVC(random_state=0)

# predict of test data

In [73]:
y_predict=clf.predict(x_test2)

# Draw confusion matrix

In [74]:
cnf_mat=confusion_matrix(y_predict,y_test2)

In [75]:
cnf_mat

array([[ 460,  164],
       [ 275, 1051]], dtype=int64)

In [76]:
clf_report=classification_report(y_predict,y_test2)

In [77]:
clf_report

'              precision    recall  f1-score   support\n\n           0       0.63      0.74      0.68       624\n           1       0.87      0.79      0.83      1326\n\n    accuracy                           0.77      1950\n   macro avg       0.75      0.76      0.75      1950\nweighted avg       0.79      0.77      0.78      1950\n'

# Now predict a future value that's not known to the model

In [82]:
df_future=df.sample(1)

In [83]:
df_future

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
1240  white            7.9              0.14         0.28             1.8   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
1240      0.041                 44.0                 178.0   0.9954  3.45   

      sulphates  alcohol  quality  
1240       0.43      9.2        6

In [84]:
df_future.shape

(1, 13)

In [85]:
x_future=df_future.drop(['type','quality'],axis=1)

In [86]:
x_future

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1240            7.9              0.14         0.28             1.8      0.041   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1240                 44.0                 178.0   0.9954  3.45       0.43   

      alcohol  
1240      9.2

In [88]:
x_future=scalar.fit_transform(x_future)

In [89]:
y_pred_future=clf.predict(x_future)

In [90]:
y_pred_future

array([1], dtype=int64)

In [93]:
df.quality[1]

6

# As you can see that the value at that position in the original dataset is 6 means it's made 1 by lambda function and the model has predicted it as one that's all thank you!!